const INCREMENT_PRODUCTS = 'INCREMENT_PRODUCTS';
const INCREMENT_BADGE='INCREMENT_BADGE'
const NAME_VAL = 'NAME_VAL';
const MIDDLE_VAL = 'MIDDLE_VAL';
const LASTNAME_VAL = 'LASTNAME_VAL';
const AGE_VAL = 'AGE_VAL';
const COUNTRY_VAL = 'COUNTRY_VAL';
const SEX_VAL = 'SEX_VAL';
const EMAIL_VAL = 'EMAIL_VAL';
const PASSWORD_VAL = 'PASSWORD_VAL';
const CONTROL_LOGIN='CONTROL_LOGIN'
const IS_LOGGED='IS_LOGGED';
const TARGET_EMAIL='TARGET_EMAIL';
 const TARGET_PASSWORD='TARGET_PASSWORD';
 const GET_DATA_FROM_STORAGE='GET_DATA_FROM_STORAGE'
const UPDATE_NAME_VAL='UPDATE_NAME_VAL'
const STORAGE_IMG='STORAGE_IMG'
const TOTAL_PRODUCTS='TOTAL_PRODUCTS'
const UPDATE_IMG_PREVIEW='UPDATE_IMG_PREVIEW'


export {TOTAL_PRODUCTS,UPDATE_IMG_PREVIEW,INCREMENT_BADGE,STORAGE_IMG,UPDATE_NAME_VAL,GET_DATA_FROM_STORAGE,TARGET_EMAIL,TARGET_PASSWORD,NAME_VAL,MIDDLE_VAL,LASTNAME_VAL,AGE_VAL,COUNTRY_VAL,SEX_VAL,INCREMENT_PRODUCTS,EMAIL_VAL,PASSWORD_VAL,CONTROL_LOGIN,IS_LOGGED}
